import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{readFileSync}from'node:fs';import{spawn,spawnSync}from'node:child_process';import{fileURLToPath}from'node:url';import{resolve}from'node:path';
const root=fileURLToPath(new URL('../',import.meta.url)),container=process.argv[2],db=process.argv[3];
function dx(a,input){const r=spawnSync('docker',a,{input,encoding:'utf8',timeout:120000,maxBuffer:24e6});if(r.status!==0)throw Error(r.stderr);return r.stdout.trim()}const base=['exec','-i',container,'psql','-XqAt','-U','postgres','-d',db,'-v','ON_ERROR_STOP=1','-v','VERBOSITY=verbose'];const sql=s=>dx(base,s);if(sql("select count(*) from auth.users where email='t09-race-a@x'")==='0')sql(readFileSync(resolve(root,'supabase/tests/e1_t09_concurrency_setup.sql'),'utf8'));
const auth=u=>`set local role authenticated;select set_config('request.jwt.claim.sub','${u}',true);`,A='e1095000-0000-0000-0000-000000000101',B='e1095000-0000-0000-0000-000000000102',ADMIN='e1095000-0000-0000-0000-000000000103';
function conn(n){const c=spawn('docker',['exec','-i','-e',`PGAPPNAME=${n}`,container,'psql','-XqAt','-U','postgres','-d',db,'-v','ON_ERROR_STOP=1','-v','VERBOSITY=verbose'],{stdio:['pipe','pipe','pipe']});let o='',e='';c.stdout.on('data',d=>o+=d);c.stderr.on('data',d=>e+=d);return{c,o:()=>o,done:new Promise(r=>c.on('close',code=>r({code,o,e})))}}async function until(f){let end=Date.now()+2e4;while(!f()){if(Date.now()>end)throw Error('timeout bloqueo');await new Promise(r=>setTimeout(r,100))}}
async function race(name,holderSql,waiterSql,verify){const h=conn(name+'_h');h.c.stdin.write(`begin;set local statement_timeout='30s';${holderSql};select 'READY';\n`);await until(()=>h.o().includes('READY'));const w=conn(name+'_w');w.c.stdin.end(`begin;set local statement_timeout='30s';${waiterSql};commit;\n`);await until(()=>sql(`select exists(select 1 from pg_stat_activity where application_name='${name}_w' and cardinality(pg_blocking_pids(pid))>0)`)==='t');h.c.stdin.end('commit;\n');const[hr,wr]=await Promise.all([h.done,w.done]);assert.equal(hr.code,0,hr.e);assert.notEqual(wr.code,0);assert.match(wr.e,/22023|40001/);verify();assert.equal(sql(`select count(*) from pg_stat_activity where application_name in('${name}_h','${name}_w')`),'0');console.log('PASS '+name)}
async function raceBoth(name,holderSql,waiterSql,verify){const h=conn(name+'_h');h.c.stdin.write(`begin;set local statement_timeout='30s';${holderSql};select 'READY';\n`);await until(()=>h.o().includes('READY'));const w=conn(name+'_w');w.c.stdin.end(`begin;set local statement_timeout='30s';${waiterSql};commit;\n`);await until(()=>sql(`select exists(select 1 from pg_stat_activity where application_name='${name}_w' and cardinality(pg_blocking_pids(pid))>0)`)==='t');h.c.stdin.end('commit;\n');const[hr,wr]=await Promise.all([h.done,w.done]);assert.equal(hr.code,0,hr.e);assert.equal(wr.code,0,wr.e);verify();assert.equal(sql(`select count(*) from pg_stat_activity where application_name in('${name}_h','${name}_w')`),'0');console.log('PASS '+name)}
const pay=(u,p,s,n,t=n===100?'TOTAL':'PARCIAL')=>`${auth(u)}select * from public.rpc_registrar_cobro_pedido(${p},'${s}','${t}','[{"medio":"EFECTIVO","importe":${n/2},"propina":0},{"medio":"YAPE","importe":${n/2},"propina":0}]'::jsonb,'${randomUUID()}')`;
await race('t09_final',pay(A,-10951,'e1095000-0000-0000-0000-000000000401',100),pay(B,-10951,'e1095000-0000-0000-0000-000000000401',100),()=>{assert.equal(sql("select estado||'|'||(select estado from mesa where id=p.mesa_id)||'|'||(select sum(importe) from pago where pedido_id=p.id)||'|'||(select count(*) from cobro where pedido_id=p.id)||'|'||(select count(*) from auditoria_caja where pedido_id=p.id and tipo='PAGO') from pedido p where id=-10951"),'PAGADO|LIBRE|100.00|1|1')});
await race('t09_partial',pay(A,-10952,'e1095000-0000-0000-0000-000000000401',60),pay(B,-10952,'e1095000-0000-0000-0000-000000000401',60),()=>{assert.equal(sql("select estado||'|'||(select estado from mesa where id=p.mesa_id)||'|'||(select sum(importe) from pago where pedido_id=p.id) from pedido p where id=-10952"),'ENTREGADO|PENDIENTE_PAGO|60.00')});
await race('t09_close',`${auth(A)}select public.rpc_cerrar_sesion_caja('e1095000-0000-0000-0000-000000000402',0,null,'${randomUUID()}')`,pay(B,-10953,'e1095000-0000-0000-0000-000000000402',100),()=>{assert.equal(sql("select estado from sesion_caja where id='e1095000-0000-0000-0000-000000000402'"),'CERRADA');assert.equal(sql('select count(*) from pago where pedido_id=-10953'),'0')});
await race('t09_annul',`${auth(ADMIN)}select public.anular_pedido_supervisado(-10954,'Carrera','${randomUUID()}')`,pay(B,-10954,'e1095000-0000-0000-0000-000000000403',100),()=>{assert.equal(sql("select estado||'|'||(select estado from mesa where id=p.mesa_id)||'|'||(select count(*) from pago where pedido_id=p.id) from pedido p where id=-10954"),'ANULADO|LIBRE|0')});
sql(`begin;${auth(A)}select public.rpc_solicitar_descuento_pedido(-10955,20,null,'Carrera descuento','${randomUUID()}');commit;`);
await raceBoth('t09_discount',`${auth(ADMIN)}select public.rpc_decidir_descuento_pedido(-10955,'AUTORIZAR',null,'${randomUUID()}')`,pay(B,-10955,'e1095000-0000-0000-0000-000000000401',80,'TOTAL'),()=>{assert.equal(sql("select estado||'|'||(select total_neto from fn_resolver_total_pedido(p.id))||'|'||(select sum(importe) from pago where pedido_id=p.id)||'|'||(select count(*) from cobro where pedido_id=p.id) from pedido p where id=-10955"),'PAGADO|80.00|80.00|1')});
assert.equal(sql("select count(*) from auditoria_caja a left join cobro c on c.id=a.cobro_id where a.tipo='PAGO' and c.id is null"),'0');console.log('PASS cinco carreras T09 delta; sin sobrepago/huérfanos/residuos');
