import assert from 'node:assert/strict';import{randomUUID}from'node:crypto';import{readFileSync,readdirSync}from'node:fs';import{spawnSync}from'node:child_process';import{fileURLToPath}from'node:url';import{resolve}from'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));const container=process.argv[2];assert.match(container??'',/^mikuyapp-e1-t09-validation-[a-z0-9-]+$/);
function docker(args,input){const r=spawnSync('docker',args,{input,encoding:'utf8',timeout:120000,maxBuffer:32*1024*1024});if(r.error||r.status!==0)throw new Error(r.error?.message??r.stderr);return r.stdout.trim();}
const[meta]=JSON.parse(docker(['inspect',container]));assert.equal(meta.HostConfig.NetworkMode,'none');assert.equal(meta.Mounts.some(m=>m.Type==='bind'),false);assert.match(meta.Config.Image,/^public\.ecr\.aws\/supabase\/postgres:17\./);
const database=`e1_t09_${randomUUID().replaceAll('-','')}`;docker(['exec',container,'createdb','-U','postgres','--template=template0',database]);console.log(`LOCAL ISOLATED: ${container}/${database}`);
const args=['exec','-i',container,'psql','-XqAt','-U','postgres','-d',database,'-v','ON_ERROR_STOP=1','-v','VERBOSITY=verbose'];const sql=s=>docker(args,s);const file=p=>sql(readFileSync(resolve(root,p),'utf8'));
docker(['exec','-i',container,'psql','-XqAt','-U','supabase_admin','-d',database,'-v','ON_ERROR_STOP=1'],docker(['exec',container,'pg_dump','-U','supabase_admin','-d','postgres','--schema-only']));
sql("alter default privileges for role postgres in schema public revoke select,insert,update,delete on tables from anon,authenticated,service_role;alter default privileges for role postgres in schema public revoke select,usage on sequences from anon,authenticated,service_role;alter default privileges for role postgres in schema public revoke execute on functions from public,anon,authenticated,service_role;");
const target='20260918000100_e1_delta_t09_cobro_atomico.sql';const migrations=readdirSync(resolve(root,'supabase/migrations')).filter(f=>f.endsWith('.sql')&&f<=target).sort();assert.equal(migrations.at(-1),target);for(const m of migrations)file(`supabase/migrations/${m}`);file('supabase/seed.sql');
const types=sql("select string_agg(distinct tipo,',' order by tipo) from public.auditoria_caja");assert.equal(types,'');
const def=sql("select pg_get_constraintdef(oid) from pg_constraint where conrelid='public.auditoria_caja'::regclass and conname='ck_auditoria_caja_t09'");for(const event of ['APERTURA','ENTRADA','SALIDA','CIERRE','CIERRE_SUPERVISOR','SOLICITUD_DESCUENTO','AUTORIZACION_DESCUENTO','RECHAZO_DESCUENTO','ANULACION','PAGO'])assert.match(def,new RegExp(event));
assert.match(sql("select pg_get_functiondef('public.rpc_registrar_pago_pedido_v2(bigint,uuid,numeric,text,numeric,uuid)'::regprocedure)"),/rpc_registrar_cobro_pedido/i);
assert.match(sql("select pg_get_functiondef('public.rpc_registrar_cobro_pedido(bigint,uuid,text,jsonb,uuid)'::regprocedure)"),/sesion_caja[\s\S]*for update[\s\S]*pedido[\s\S]*for update[\s\S]*mesa[\s\S]*for update/i);
assert.equal(sql("select count(*) from public.pago where cobro_id is not null"),'0');
console.log(`PASS replay limpio ${migrations.length} migraciones; legacy sin cabeceras; cobro atómico y locks sesión-pedido-mesa.`);console.log(`DATABASE=${database}`);
