// Validación incremental T07 en PostgreSQL local aislado y sin red.
import assert from 'node:assert/strict';import{randomUUID}from'node:crypto';import{readFileSync,readdirSync}from'node:fs';import{spawn,spawnSync}from'node:child_process';import{fileURLToPath}from'node:url';import{resolve}from'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));const container=process.argv[2];assert.match(container??'',/^mikuyapp-e1-t07-validation-[a-z0-9-]+$/);
function docker(args,input){const r=spawnSync('docker',args,{input,encoding:'utf8',timeout:120000,maxBuffer:24*1024*1024});if(r.error||r.status!==0)throw new Error(r.error?.message??r.stderr);return r.stdout.trim();}
const[meta]=JSON.parse(docker(['inspect',container]));assert.equal(meta.HostConfig.NetworkMode,'none');assert.equal(meta.Mounts.some(m=>m.Type==='bind'),false);assert.match(meta.Config.Image,/^public\.ecr\.aws\/supabase\/postgres:17\./);
const database=`e1_t07_${randomUUID().replaceAll('-','')}`;docker(['exec',container,'createdb','-U','postgres','--template=template0',database]);console.log(`LOCAL ISOLATED: ${container}/${database}`);const args=['exec','-i',container,'psql','-XqAt','-U','postgres','-d',database,'-v','ON_ERROR_STOP=1','-v','VERBOSITY=verbose'];const sql=s=>docker(args,s);const file=p=>sql(readFileSync(resolve(root,p),'utf8'));
docker(['exec','-i',container,'psql','-XqAt','-U','supabase_admin','-d',database,'-v','ON_ERROR_STOP=1'],docker(['exec',container,'pg_dump','-U','supabase_admin','-d','postgres','--schema-only']));sql(`alter default privileges for role postgres in schema public revoke select,insert,update,delete on tables from anon,authenticated,service_role;alter default privileges for role postgres in schema public revoke select,usage on sequences from anon,authenticated,service_role;alter default privileges for role postgres in schema public revoke execute on functions from public,anon,authenticated,service_role;`);
const target='20260914000300_e1_t07_anulacion_administrativa.sql';const baseline=readdirSync(resolve(root,'supabase/migrations')).filter(f=>f.endsWith('.sql')&&f<target).sort();assert.equal(baseline.length,33);for(const m of baseline)file(`supabase/migrations/${m}`);file('supabase/seed.sql');file('supabase/tests/e1_t03_fixture.sql');file(`supabase/migrations/${target}`);
console.log(file('supabase/tests/e1_t07_anulacion_administrativa.sql').split('\n').filter(s=>s.includes('E1-T07 SQL:')).join('\n'));
file('supabase/tests/e1_t04_fixture.sql');for(const regression of ['e1_t04_apertura_sesion','e1_t05_movimientos_cierre','e1_t06_descuento_pedido']){file(`supabase/tests/${regression}.sql`);console.log(`PASS regresión de auditoría directamente afectada: ${regression}`);}
file('supabase/tests/e1_t07_concurrency_setup.sql');
function connection(name){const child=spawn('docker',['exec','-i','-e',`PGAPPNAME=${name}`,container,'psql','-XqAt','-U','postgres','-d',database,'-v','ON_ERROR_STOP=1','-v','VERBOSITY=verbose'],{stdio:['pipe','pipe','pipe']});let output='',error='';child.stdout.on('data',d=>output+=d);child.stderr.on('data',d=>error+=d);const done=new Promise((resolve,reject)=>{child.on('error',reject);child.on('close',code=>resolve({code,output,error}))});return{child,done,output:()=>output};}
async function until(f,label){const end=Date.now()+20000;while(!f()){if(Date.now()>end)throw new Error(`Timeout ${label}`);await new Promise(r=>setTimeout(r,100));}}
const auth=u=>`set local role authenticated;select set_config('request.jwt.claim.sub','${u}',true);`;
const admin=connection('e1_t07_annul_holder');let payer;
try{
 admin.child.stdin.write(`begin;set local statement_timeout='30s';${auth('e1075000-0000-0000-0000-000000000101')}select public.anular_pedido_supervisado(-10759,'Anulación concurrente','${randomUUID()}');select 'HOLDER_READY';\n`);
 await until(()=>admin.output().includes('HOLDER_READY'),'anulación sin commit');
 payer=connection('e1_t07_payment_waiter');payer.child.stdin.end(`begin;set local statement_timeout='30s';${auth('e1075000-0000-0000-0000-000000000102')}select to_jsonb(r) from public.rpc_registrar_pago_total_pedido(-10759,'e1075000-0000-0000-0000-000000000401','EFECTIVO',0,'${randomUUID()}')r;commit;\n`);
 await until(()=>sql("select exists(select 1 from pg_stat_activity where application_name='e1_t07_payment_waiter' and cardinality(pg_blocking_pids(pid))>0)")==='t','cobro bloqueado por anulación');admin.child.stdin.end('commit;\n');const[a,p]=await Promise.all([admin.done,payer.done]);assert.equal(a.code,0,a.error);assert.notEqual(p.code,0);assert.match(p.error,/40001/);
 assert.equal(sql('select estado from public.pedido where id=-10759'),'ANULADO');assert.equal(sql("select estado from public.mesa where id='e1075000-0000-0000-0000-000000000503'"),'LIBRE');assert.equal(sql('select count(*) from public.pago where pedido_id=-10759'),'0');assert.equal(sql("select count(*) from public.historial_estado where pedido_id=-10759 and estado_nuevo='ANULADO'"),'1');assert.equal(sql("select count(*) from public.auditoria_caja where pedido_id=-10759 and tipo='ANULACION'"),'1');assert.equal(sql("select count(*) from pg_stat_activity where application_name in('e1_t07_annul_holder','e1_t07_payment_waiter')"),'0');console.log('PASS TP29 carrera real: anulación ganó, cobro esperó y falló 40001; cero pago inconsistente');
}finally{admin.child.stdin.destroy();admin.child.kill();payer?.child.stdin.destroy();payer?.child.kill();}
console.log('PASS T07 incremental: TP26–TP30 y regresiones de auditoría directamente afectadas.');
