create extension if not exists pgcrypto with schema extensions;

create table public.local (
  id uuid not null default gen_random_uuid(),
  codigo text not null,
  nombre text not null,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  constraint pk_local primary key (id)
);

create table public.rol (
  id smallint generated by default as identity not null,
  codigo text not null,
  nombre text not null,
  activo boolean not null default true,
  constraint pk_rol primary key (id)
);

create table public.perfil_usuario (
  id uuid not null,
  local_id uuid not null,
  rol_id smallint not null,
  nombre text not null,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  constraint pk_perfil_usuario primary key (id),
  constraint fk_perfil_usuario_auth_user foreign key (id)
    references auth.users (id),
  constraint fk_perfil_usuario_local foreign key (local_id)
    references public.local (id),
  constraint fk_perfil_usuario_rol foreign key (rol_id)
    references public.rol (id)
);

create table public.mesa (
  id uuid not null default gen_random_uuid(),
  local_id uuid not null,
  codigo text not null,
  nombre text not null,
  estado text not null default 'LIBRE',
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  constraint pk_mesa primary key (id),
  constraint uq_mesa_id_local_id unique (id, local_id),
  constraint fk_mesa_local foreign key (local_id)
    references public.local (id)
);

create table public.categoria (
  id uuid not null default gen_random_uuid(),
  local_id uuid not null,
  codigo text not null,
  nombre text not null,
  orden integer not null default 0,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  constraint pk_categoria primary key (id),
  constraint uq_categoria_id_local_id unique (id, local_id),
  constraint fk_categoria_local foreign key (local_id)
    references public.local (id)
);

create table public.producto (
  id uuid not null default gen_random_uuid(),
  local_id uuid not null,
  categoria_id uuid not null,
  codigo text not null,
  nombre text not null,
  precio numeric(10,2) not null,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  constraint pk_producto primary key (id),
  constraint fk_producto_local foreign key (local_id)
    references public.local (id),
  constraint fk_producto_categoria_local foreign key (categoria_id, local_id)
    references public.categoria (id, local_id)
);

create table public.pedido (
  id bigint generated always as identity not null,
  local_id uuid not null,
  mesa_id uuid not null,
  creado_por uuid not null,
  estado text not null default 'ABIERTO',
  creado_en timestamptz not null default now(),
  enviado_en timestamptz null,
  constraint pk_pedido primary key (id),
  constraint fk_pedido_local foreign key (local_id)
    references public.local (id),
  constraint fk_pedido_creado_por foreign key (creado_por)
    references public.perfil_usuario (id),
  constraint fk_pedido_mesa_local foreign key (mesa_id, local_id)
    references public.mesa (id, local_id)
);

create table public.detalle_pedido (
  id bigint generated always as identity not null,
  pedido_id bigint not null,
  producto_id uuid not null,
  cantidad integer not null,
  precio_unitario numeric(10,2) not null,
  observacion text null,
  constraint pk_detalle_pedido primary key (id),
  constraint fk_detalle_pedido_pedido foreign key (pedido_id)
    references public.pedido (id),
  constraint fk_detalle_pedido_producto foreign key (producto_id)
    references public.producto (id)
);

create table public.historial_estado (
  id bigint generated always as identity not null,
  pedido_id bigint not null,
  estado_anterior text null,
  estado_nuevo text not null,
  usuario_id uuid not null,
  creado_en timestamptz not null default now(),
  constraint pk_historial_estado primary key (id),
  constraint fk_historial_estado_pedido foreign key (pedido_id)
    references public.pedido (id),
  constraint fk_historial_estado_usuario foreign key (usuario_id)
    references public.perfil_usuario (id)
);

create table public.pago (
  id bigint generated always as identity not null,
  pedido_id bigint not null,
  importe numeric(10,2) not null,
  medio text not null,
  usuario_id uuid not null,
  pagado_en timestamptz not null default now(),
  constraint pk_pago primary key (id),
  constraint fk_pago_pedido foreign key (pedido_id)
    references public.pedido (id),
  constraint fk_pago_usuario foreign key (usuario_id)
    references public.perfil_usuario (id)
);
